
[analyzer]
# Percentage threshold a query needs to reach to begin blocking the sender IP and sub domains 
sus_percentage_threshold = 1.0
# true to use saved blocked sub domains, false otherwise
use_blacklist = true

[logging]
# standard python logger level 
level = DEBUG
# file path to log to a file, stdout to log to stdout
output = stdout

[entropyanalyzer]
# true to enable the entropy analyzer, false otherwise 
enabled = true
# How much this analyzer contributes to the overall sus_percentage 
weight_percentage = 0.2
# Entropy required to reach 100% suspicion from the this analyzer 
max_entropy = 3.5

[trafficanalyzer]
# true to enable the traffic analyzer, false otherwise 
enabled = false
# How much this analyzer contributes to the overall sus_percentage 
weight_percentage = 1.0
# How long an IP or subdomain will be kept in history 
minute_difference_threshold = 120
# number of queries needed to reach 100% suspicion from this analyzer 
num_queries_threshold = 5

[mlanalyzer]
# true to enable the ML analzyer, false otherwise 
enabled = false
# How much this analyzer contributes to the overall sus_percentage 
weight_percentage = 1.0
# URL to the ML API 
apiurl = http://localhost:3000





